Support Lumen 11
DarkaOnLine/SwaggerLume pull request #140
Opened 2024-05-09 22:43 UTC by MarkVaughn

2024-05-10 04:33 UTC, DarkaOnLine requested changes
@MarkVaughn php8.2 tests are failing, can you check/fix?

2024-05-10 16:48 UTC, MarkVaughn commented
I think this has to do with #135 / #136

2024-05-10 17:37 UTC, MarkVaughn commented
I tried a bunch and failed. This is a crazy matrix

2024-05-15 06:09 UTC, DarkaOnLine approved these changes

2024-05-15 06:09 UTC, merged